
services:
  api:
    build: .
    container_name: plant_care_api
    ports:
      - "8000:8000"
    volumes:
      - ./photos:/app/photos
      - ./a_rosa_je.db:/app/a_rosa_je.db
    environment:
      - DATABASE_URL=sqlite:///./a_rosa_je.db
      - SECRET_KEY=your-production-secret-key-change-this
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENCRYPTION_KEY=your-secure-encryption-key-change-this-in-production
      - ENCRYPTION_ENABLED=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s