"""empty message

Revision ID: 72c7f7163820
Revises: e97b5229f548
Create Date: 2025-03-25 20:48:02.358358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c7f7163820'
down_revision: Union[str, None] = 'e97b5229f548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commentary_id'), 'commentary', ['id'], unique=False)
    op.drop_index('ix_care_requests_id', table_name='care_requests')
    op.drop_table('care_requests')
    op.add_column('plants', sa.Column('in_care_id', sa.Integer(), nullable=True))
    op.add_column('plants', sa.Column('plant_sitting', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plants', 'users', ['in_care_id'], ['id'])
    op.create_foreign_key(None, 'plants', 'users', ['plant_sitting'], ['id'])
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_column('plants', 'plant_sitting')
    op.drop_column('plants', 'in_care_id')
    op.create_table('care_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('plant_id', sa.INTEGER(), nullable=True),
    sa.Column('botanist_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['botanist_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_care_requests_id', 'care_requests', ['id'], unique=False)
    op.drop_index(op.f('ix_commentary_id'), table_name='commentary')
    op.drop_table('commentary')
    # ### end Alembic commands ###
